[project]
name = "agritwin-gh"
version = "0.1.0"
description = "AgriTwin-GH is a software-based digital twin for precision greenhouse horticulture. It integrates open-source sensor and image data with AI/ML models to predict crop health, disease risk, and growth stages, enabling predictive control, resource optimization, and human-centric decision support for tomato and strawberry cultivation."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.12.0",
    "diffusers>=0.10.0",
    "fastparquet>=2025.12.0",
    "kaggle==2.0.0",
    "keras>=3.13.2",
    "matplotlib>=3.0.0",
    "minio>=7.2.0",
    "mkdocs>=1.5.3",
    "mkdocs-awesome-pages-plugin>=2.9.2",
    "mkdocs-material>=9.5.3",
    "mkdocs-minify-plugin>=0.8.0",
    "numpy>=1.24.0",
    "opencv-python>=4.5.0",
    "opencv-python-headless>=4.5.0",
    "pandas>=2.0.0",
    "pillow>=10.0.0",
    "psycopg2-binary>=2.9.9",
    "pyarrow>=23.0.1",
    "pymdown-extensions>=10.7",
    "python-dotenv>=1.0.0",
    "pyyaml>=6.0",
    "scikit-learn>=1.0.0",
    "seaborn>=0.11.0",
    "sqlalchemy>=2.0.0",
    "tabulate>=0.9.0",
    "tensorflow>=2.0.0",
    "torch>=1.0.0",
    "tqdm>=4.65.0",
    "transformers>=5.2.0",
]
