"""
Media schemas — used by:
  ``GET /api/media/latest``        → latest stage + leaf camera images
  ``GET /api/media/stage-images``  → rolling stage camera gallery (5 frames)
  ``GET /api/media/disease-scans`` → rolling leaf-scan gallery (5 frames)

Image metadata is retrieved by ``agritwin_gh.mpc.image_streamer.ImageStreamer``
from the ``image_metadata`` table.  Actual image bytes are served via MinIO
pre-signed URLs generated by ``agritwin_gh.services.media_service``.

The ``src`` field always carries a pre-signed URL string (or an empty string
when no image is available), never raw bytes.

Frontend mock shapes
--------------------
``CROP_IMAGES`` (``mockData.js``) — used by ``HomeDashboard``::

    {
      stage: { src: '...', alt: '...', badge: 'Day 12',
               location: 'GH-04 · Camera 2', captured: '1 hr ago' },
      leaf:  { src: '...', alt: '...', badge: '99.5% Conf.',
               location: 'Sector B · Leaf #7', captured: '2 mins ago' }
    }

``RECENT_CROP_IMAGES`` — used by ``DetailedInsights`` (5-frame gallery)::

    { src, alt, capturedAgo, stage, confidence }

``RECENT_LEAF_IMAGES`` — used by ``DetailedInsights`` (5-frame gallery)::

    { src, alt, capturedAgo, classification, risk, confidence }

Design note
-----------
Three image entry types are defined:
  - ``ImageEntry``       — base type used in ``LatestMediaResponse``.
  - ``StageImageEntry``  — specialised for stage camera frames (adds ``stage``,
                            ``confidence``).
  - ``LeafScanEntry``    — specialised for disease scan frames (adds
                            ``classification``, ``risk``, ``confidence``).
"""

from __future__ import annotations

from pydantic import BaseModel, Field


# ── Base image entry (latest media) ───────────────────────────────────────────


class ImageEntry(BaseModel):
    """Metadata and URL for a single camera or scan image.

    Used in ``LatestMediaResponse`` (Dashboard crop images panel).
    Matches the ``CROP_IMAGES.stage`` and ``CROP_IMAGES.leaf`` shapes
    from ``mockData.js``.

    Example::

        {
          "src": "https://minio.local/agritwin/gh04-cam2-20260404T091500.jpg?X-Amz-...",
          "alt": "Tomato plant at Flowering stage, GH-04 Camera 2",
          "badge": "Day 12",
          "location": "GH-04 · Camera 2",
          "captured": "1 hr ago",
          "image_key": "greenhouse/gh04-cam2-20260404T091500.jpg",
          "bucket_name": "agritwin-images"
        }
    """

    src: str = Field(
        default="",
        description="MinIO pre-signed URL valid for ~15 minutes, or empty string "
                    "if no image is available for this slot.",
    )
    alt: str = Field(
        default="",
        description="Accessible alt-text for screen readers and broken-image states.",
    )
    badge: str = Field(
        default="",
        description="Overlay badge text shown on the image frame, "
                    "e.g. 'Day 12' for stage images or '99.5% Conf.' for leaf scans.",
    )
    location: str = Field(
        default="",
        description="Camera or sector description, e.g. 'GH-04 · Camera 2'.",
    )
    captured: str = Field(
        default="",
        description="Human-readable recency string, e.g. '1 hr ago', '2 mins ago'.",
    )
    image_key: str = Field(
        default="",
        description="MinIO object key for debugging / cache invalidation.",
    )
    bucket_name: str = Field(
        default="",
        description="MinIO bucket name the image was retrieved from.",
    )


class LatestMediaResponse(BaseModel):
    """Response for ``GET /api/media/latest``.

    Returns exactly two images — one stage-camera frame and one leaf-scan frame —
    matching the ``CROP_IMAGES`` constant consumed by ``HomeDashboard``.

    When no image is available for a slot, the ``src`` field is an empty string
    and ``badge`` / ``location`` carry placeholder text.
    """

    stage: ImageEntry
    leaf: ImageEntry


# ── Stage camera gallery ───────────────────────────────────────────────────────


class StageImageEntry(BaseModel):
    """One frame in the rolling stage-camera gallery.

    Used in ``StageImagesResponse.images``.  Matches the ``RECENT_CROP_IMAGES``
    array consumed by ``DetailedInsights`` ``ImageFrame`` components (5 frames).

    Example::

        {
          "src": "https://minio.local/...",
          "alt": "Greenhouse stage camera — Flowering, GH-04",
          "captured_ago": "30 mins ago",
          "stage": "Flowering",
          "confidence": 97.3,
          "image_key": "greenhouse/gh04-cam2-20260404T085500.jpg",
          "bucket_name": "agritwin-images"
        }
    """

    src: str = Field(
        default="",
        description="MinIO pre-signed URL, or empty string if unavailable.",
    )
    alt: str = Field(
        default="",
        description="Accessible alt-text for the image frame.",
    )
    captured_ago: str = Field(
        default="",
        description="Human-readable recency, e.g. '30 mins ago'. "
                    "Frontend field: capturedAgo.",
    )
    stage: str = Field(
        default="",
        description="Title-cased growth stage label at time of capture, "
                    "e.g. 'Flowering'.",
    )
    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=100.0,
        description="Growth-stage classifier confidence at capture time (0–100).",
    )
    image_key: str = Field(default="", description="MinIO object key.")
    bucket_name: str = Field(default="", description="MinIO bucket name.")


class StageImagesResponse(BaseModel):
    """Response for ``GET /api/media/stage-images``.

    Returns the five most recent stage-camera frames, newest first.
    The ``images`` list may contain fewer than five entries if not enough
    images have been captured yet.
    """

    images: list[StageImageEntry]


# ── Leaf / disease scan gallery ────────────────────────────────────────────────


class LeafScanEntry(BaseModel):
    """One frame in the rolling leaf-scan gallery.

    Used in ``DiseaseImagesResponse.images``.  Matches the ``RECENT_LEAF_IMAGES``
    array consumed by ``DetailedInsights`` ``ImageFrame`` components (5 frames).

    The ``classification`` and ``risk`` fields come from the disease classifier
    run on this specific image.  They may differ from the aggregate
    ``DiseaseRisksResponse.dominant_label`` because they reflect a point-in-time
    scan rather than the running weighted average.

    Example::

        {
          "src": "https://minio.local/...",
          "alt": "Leaf scan — Sector B · Leaf #7",
          "captured_ago": "2 mins ago",
          "classification": "healthy leaves",
          "risk": 2.1,
          "confidence": 99.5,
          "image_key": "scans/sectorb-leaf7-20260404T091300.jpg",
          "bucket_name": "agritwin-scans"
        }
    """

    src: str = Field(
        default="",
        description="MinIO pre-signed URL, or empty string if unavailable.",
    )
    alt: str = Field(
        default="",
        description="Accessible alt-text for the image frame.",
    )
    captured_ago: str = Field(
        default="",
        description="Human-readable recency, e.g. '2 mins ago'. "
                    "Frontend field: capturedAgo.",
    )
    classification: str = Field(
        default="healthy leaves",
        description="Canonical disease label assigned by the classifier to this "
                    "specific scan, e.g. 'healthy leaves' or 'late blight'.",
    )
    risk: float = Field(
        default=0.0,
        ge=0.0,
        le=100.0,
        description="Disease risk score for this scan as a percentage (0–100). "
                    "Frontend field: risk.",
    )
    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=100.0,
        description="Classifier confidence for the ``classification`` above (0–100). "
                    "Shown as a badge overlay on the scan frame.",
    )
    image_key: str = Field(default="", description="MinIO object key.")
    bucket_name: str = Field(default="", description="MinIO bucket name.")


class DiseaseImagesResponse(BaseModel):
    """Response for ``GET /api/media/disease-scans``.

    Returns the five most recent leaf-scan frames, newest first, with
    per-image disease classification and confidence scores.
    """

    images: list[LeafScanEntry]
