"""
inference.py — AgriTwin-GH Tomato Disease Classifier
Deployment-ready inference module. Generated by Task-2 notebook.

Usage (standalone):
    from src.agritwin_gh.models.inference import load_inference_assets, predict_image

    model, label_map = load_inference_assets(
        model_path     = "src/agritwin_gh/models/<run_id>.keras",
        label_map_path = "src/agritwin_gh/models/artifacts/<run_id>/label_map.json",
    )
    result = predict_image(image_input="/path/to/leaf.jpg",
                           inference_model=model,
                           loaded_label_map=label_map)
    print(result)
"""

from __future__ import annotations

import json
import pathlib
from typing import Dict, List, Tuple, Union

import numpy as np
import tensorflow as tf
from tensorflow import keras


# ── Supported backbone → preprocess_input mapping ────────────────────────────
_BACKBONE_PREPROCESS_MAP: Dict[str, object] = {
    "EfficientNetB0"   : keras.applications.efficientnet.preprocess_input,
    "EfficientNetB3"   : keras.applications.efficientnet.preprocess_input,
    "ResNet50"         : keras.applications.resnet.preprocess_input,
    "MobileNetV3Large" : keras.applications.mobilenet_v3.preprocess_input,
    "DenseNet121"      : keras.applications.densenet.preprocess_input,
}


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def load_inference_assets(
    model_path     : Union[str, pathlib.Path],
    label_map_path : Union[str, pathlib.Path],
) -> Tuple[keras.Model, dict]:
    """
    Load a saved Keras model and the corresponding label_map.json.

    Args:
        model_path     : Path to the .keras (or SavedModel) file.
        label_map_path : Path to label_map.json saved by Task-1 training.

    Returns:
        (model, label_map_dict)
    """
    model = keras.models.load_model(str(model_path))
    with open(str(label_map_path), "r") as f:
        label_map = json.load(f)
    return model, label_map


def decode_image_bytes_to_tensor(
    image_bytes   : bytes,
    image_size    : Tuple[int, int],
    preprocess_fn,
) -> tf.Tensor:
    """
    Decode raw image bytes into a preprocessed, batch-ready tf.Tensor.

    This is the SINGLE decoding entry-point for byte-based image input so
    that MinIO-fetched bytes can be fed into the model without core rewrites.

    Args:
        image_bytes  : Raw bytes of any supported image format (JPEG, PNG, …).
        image_size   : (H, W) — must match training CONFIG image_size.
        preprocess_fn: Backbone-specific normalisation callable.

    Returns:
        tf.Tensor of shape (1, H, W, 3), dtype float32.
    """
    H, W = image_size
    image = tf.image.decode_image(
        tf.constant(image_bytes),
        channels          = 3,
        expand_animations = False,
    )
    image = tf.image.resize(image, [H, W])
    image = tf.cast(image, tf.float32)
    image = preprocess_fn(image)
    image = tf.expand_dims(image, axis=0)   # add batch dim
    return image


def predict_image(
    image_input     : Union[str, bytes, pathlib.Path],
    inference_model : keras.Model,
    loaded_label_map: dict,
    top_k           : int = 3,
) -> dict:
    """
    Run inference on a single image.

    Args:
        image_input      : File path (str / Path) OR raw bytes.
        inference_model  : Loaded Keras model.
        loaded_label_map : Dict from label_map.json.
        top_k            : Number of top classes to return.

    Returns:
        {
            "class_name" : str,
            "confidence" : float,
            "probs"      : {label: float, ...},
            "topk"       : [(label, float), ...],
            "input_mode" : "path" | "bytes",
        }
    """
    backbone_name = loaded_label_map["backbone"]
    preprocess_fn = _BACKBONE_PREPROCESS_MAP.get(backbone_name)
    if preprocess_fn is None:
        raise ValueError(
            f"Backbone '{backbone_name}' not in _BACKBONE_PREPROCESS_MAP."
        )

    img_size_hw  = tuple(loaded_label_map["image_size"])
    idx_to_label = {int(k): v for k, v in loaded_label_map["idx_to_label"].items()}

    # -- Input resolution ---
    if isinstance(image_input, (str, pathlib.Path)):
        fpath = pathlib.Path(image_input)
        if not fpath.exists():
            raise FileNotFoundError(f"Image file not found: {fpath}")
        image_bytes = fpath.read_bytes()
        input_mode  = "path"
    elif isinstance(image_input, (bytes, bytearray)):
        image_bytes = bytes(image_input)
        input_mode  = "bytes"
    else:
        raise ValueError(
            f"image_input must be str, pathlib.Path, or bytes. "
            f"Got: {type(image_input).__name__}"
        )

    input_tensor = decode_image_bytes_to_tensor(image_bytes, img_size_hw, preprocess_fn)
    prob_vector  = inference_model.predict(input_tensor, verbose=0)[0].astype(float)

    pred_idx    = int(np.argmax(prob_vector))
    class_name  = idx_to_label[pred_idx]
    confidence  = float(prob_vector[pred_idx])
    probs_dict  = {idx_to_label[i]: float(prob_vector[i]) for i in range(len(prob_vector))}
    top_k_pairs = sorted(probs_dict.items(), key=lambda kv: kv[1], reverse=True)[:top_k]

    return {
        "class_name" : class_name,
        "confidence" : confidence,
        "probs"      : probs_dict,
        "topk"       : top_k_pairs,
        "input_mode" : input_mode,
    }
